spring:
   profiles: default
   cloud:
     config:
       enabled: false
     azure:
       eventhub:
         connection-string: Endpoint=sb://pearson-spring-cloud-eventhub-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=5kOTSnL/kVpYA4DwPBYN2SHGa/cYsHKrzMKMyVTCKFA=
         checkpoint-storage-account: pearsonspringcloud
         checkpoint-access-key: enBxdwD57CHpOHEkQOWbxqdDn6j35GDf7WUlO+8YdoscrDNoBe+WYMBtSRUYuxSnEdlakMrs/Jvvieoa23p1tg==
         checkpoint-container: pearsonspringcloudcontainer

     stream:
       bindings:
         consume-in-0:
           destination: ref-arch-poc
           group: employee-svc
         supply-out-0:
           destination: ref-arch-poc

       eventhub:
         bindings:
           consume-in-0:
             consumer:
               checkpoint-mode: MANUAL
       function:
         definition: consume;supply;
       poller:
         initial-delay: 0
         fixed-delay: 1000
